### ISSUE TITLE
Enable placing one shape inside another

### ISSUE THREAD

**Issue by jintonic** [jintonic/shine#2]
If shape A is inside shape B, A will be moved or rotated together with B when B is moved or rotated. The coordinates of the center of A should be with respect to the center of B, not the center of the global scene.

**Comment by bestdeveloper23** [comment]
softangel0090@gmail.com
This is my email.
You can invite me to your slack channel.
I know slalck is good for collaboration.

**Comment by bestdeveloper23** [comment]
It works.

**Comment by jintonic** [comment]
It is already there
