### ISSUE TITLE
Fix Geant4 NIST material name cases

### ISSUE THREAD

**Issue by jintonic** [jintonic/shine#27]
Currently, all material names are capitalized, for example, G4_PB. But it should be G4_Pb. Please follow strictly the names on this page: <https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/html/Appendix/materialNames.html>.

**Comment by bestdeveloper23** [comment]
I fixed and updated code.

**Comment by jintonic** [comment]
Thank you! G4_1H2 to G4_1Xe should be G4_lxx, it's an 'l', not '1'

**Comment by bestdeveloper23** [comment]
https://monosnap.com/file/aDyPg9Yu8JnMSlJHyn0aCPctjdbSdJ
I thought this is "1".
Do you mean the English letter "l"?

**Comment by jintonic** [comment]
Yes, it is the l in lucky, not number 1

**Comment by bestdeveloper23** [comment]
I see
