### ISSUE TITLE
Enable Boolean operation

### ISSUE THREAD

**Issue by jintonic** [jintonic/shine#3]
If shape A and B overlap with each other in space, 

- [x] one can choose to keep the overlapped part and remove the not overlapped parts (subtraction)
- [x] one can choose to merge two shapes into one (addition)

**Comment by bestdeveloper23** [comment]
This is my personal email.
chanlloydmanolo17@gmail.com
I'd like to work together via email.
Thank you.

**Comment by bestdeveloper23** [comment]
I have made a lot of progress on the project.
I added icons and signals.
![Annotation 2023-11-10 003731](https://github.com/jintonic/shine/assets/125925304/dffad286-80e8-47e0-aaf8-18495dd004a5)
