### ISSUE TITLE
create all basic shapes available in Geant4

### ISSUE THREAD

**Issue by jintonic** [jintonic/shine#4]
The list of all basic shapes in Geant4 can be found here: <https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/html/Detector/Geometry/geomSolids.html#constructed-solid-geometry-csg-solids>

- [x] create a panel like the one on the left of <http://polar.psi.ch/cadmc/converter/index.php> for users to select shapes
- [x] add missing shapes
- [ ] turn Capsule, circle, dodecahedron, octahedron, lathe as boolean shapes

**Comment by bestdeveloper23** [comment]
" turn Capsule, circle, dodecahedron, octahedron, lathe as boolean shapes":  what is this mean?

**Comment by jintonic** [comment]
We can worry about this part later. Those shapes do not exist in Geant4. They don't have to be in the left panel. But we can provide them in another panel (or a tab on top of the left panel) after we finish the left panel.
